jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0-209.1.beta'
          channel: 'beta'

      - run: flutter pub get
      - run: flutter build web
